### ISSUE TITLE
Títulos dos projetos

### ISSUE THREAD

**Issue by gabsprates** [globocom/opensource#6]
Para evitar que os títulos não quebrem a linha em telas menores, exemplo:

![captura de tela de 2017-06-20 17-37-08](https://user-images.githubusercontent.com/12635603/27354806-41810f7e-55df-11e7-8c76-2035fd5ca07d.png)

Sugiro colocar um `overflow-wrap: break-word;` para o h2, por meio de uma classe, no arquivo [`assets/css/main.less`](https://github.com/globocom/opensource/blob/master/assets/css/main.less#L85), assim:

```css
.project {
  /* ... */
  .container-inner {
    /* ... */
    .project-title {
      overflow-wrap: break-word;
    }
  }
}
```
